name: drupal9
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        # Support debugging CLI with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
